language: python
python: "3.4"

install:
  - "pip install pep8"
  - "pip install coveralls"
  - "pip install shapely"

before_script: "pep8 . --ignore=W293,E501"

script: coverage run --source=test_feature test_feature.py

after_success:
  coveralls