language: python
python: "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qqy python3-scipy

install:
  - "pip install pep8"
  - "pip install coveralls"
  - "pip install shapely"
  - "pip install pillow"

before_script: "pep8 . --ignore=W293,E501"

script:
  coverage run -m unittest discover

after_success:
  COVERALLS_REPO_TOKEN=N8coUcWml4g9LW7cbylJsmbO2JskCOZtm coveralls
