language: python
python: "3.4"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - "conda install --yes python=$TRAVIS_PYTHON_VERSION scipy"
  - "pip install pep8"
  - "pip install coveralls"
  - "pip install shapely"
  - "pip install pillow"

before_script: "pep8 . --ignore=W293,E501"

script:
  coverage run -m unittest discover

after_success:
  COVERALLS_REPO_TOKEN=N8coUcWml4g9LW7cbylJsmbO2JskCOZtm coveralls
