language: python
python: "3.4"

install:
  - "pip install pep8 --no-cache-dir"
  - "pip install coveralls --no-cache-dir"
  - "pip install shapely --no-cache-dir"
  - "pip install pillow --no-cache-dir"

before_script: "pep8 . --ignore=W293,E501"

script:
  coverage run -m unittest discover

after_success:
  - COVERALLS_REPO_TOKEN=N8coUcWml4g9LW7cbylJsmbO2JskCOZtm
  - coveralls
