language: python
python: "3.4"

install:
  - "pip install pep8 --no-cache-dir"
  - "pip install coveralls --no-cache-dir"
  - "pip install shapely --no-cache-dir"

before_script: "pep8 . --ignore=W293,E501"

script:
  - coverage run --source=test_feature test_feature.py
  - coverage run --source=test_feature_tree test_feature_tree.py

after_success:
  coveralls